version: '2'
services:
  logstash:
    build: logstash/
    container_name: main_logstash
    command: -f /etc/logstash/conf.d/ -w 8
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - docker_elk

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch -E node.name="es1" -E cluster.name="mycluster" -E discovery.zen.ping.unicast.hosts="192.168.154.93"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
