version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - TZ=Asia/Taipei
      - cluster.name=docker-cluster
      - http.host=0.0.0.0
      - http.port=9200
      - transport.host=127.0.0.1
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    volumes:
      - storage:/usr/share/elasticsearch/data
    networks:
      - docker_elk

  logstash:
    build: logstash/
    container_name: main_logstash
    environment:
      - TZ=Asia/Taipei
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.url=elasticsearch:9200
    command: -f /etc/logstash/conf.d/ -w 8
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    environment:
      - http.host=0.0.0.0
      - server.name=kibana
      - elasticsearch.url=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

volumes:
    storage:
        driver: local

networks:
  docker_elk:
    driver: bridge
