FROM kibana:5

#WORKDIR ${KIBANA_HOME}
#RUN gosu kibana kibana plugin --install https://github.com/dlumbrer/kbn_network/archive/master.zip
#RUN gosu kibana kibana plugin --install sirensolutions/kibi-radar-chart-plugin/0.1.0
#RUN cd /bin && kibana-plugin install x-pack
