# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601

# This setting specifies the IP address of the back end server.
server.host: "0.0.0.0"

# The Kibana server's name.  This is used for display purposes.
server.name: kibana

# The URL of the Elasticsearch instance to use for all your queries.
elasticsearch.hosts: ["http://elasticsearch:9200"]
